workplace:
    restart: always
    image: easyswoole:0.02
    links:
        - redis
        - mysql
    ports:
        - "9521:9501"
        - "9522:9502"
        - "9523:9503"
        - "9527:9527"
    volumes:
        #- /etc/localtime:/etc/localtime
        - /Users/chenishr/www/html:/var/www/html
