FROM php:7.2.5-fpm-alpine3.7

ARG TZ=UTC
ARG PHP_TIMEZONE=UTC

ENV TZ $TZ

RUN apk update \
    && apk add tzdata linux-headers \
    && cp /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo "date.timezone=$PHP_TIMEZONE" > "$PHP_INI_DIR/conf.d/date-timezone.ini" \
    && apk add $PHPIZE_DEPS \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install mysqli pdo_mysql \
    && apk add freetype libpng libjpeg-turbo \
    && apk add freetype-dev libpng-dev libjpeg-turbo-dev \
    && docker-php-ext-configure gd \
        --with-freetype-dir=/usr/include/ \
        --with-png-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install opcache

######################################
# install redis
######################################

COPY	./redis-3.1.5RC1.tgz /tmp/
RUN		cd /usr/src \
		&& tar -zxf /tmp/redis-3.1.5RC1.tgz \
			&& (\
				cd redis-3.1.5RC1 \
				&& /usr/local/bin/phpize \
				&& ./configure \
				&& make && make install \
			 )\
		&& rm /tmp/redis-3.1.5RC1.tgz \
		&& docker-php-ext-enable redis


CMD ["php-fpm"]
