nginx:
    image: index.alauda.cn/library/nginx
    links:
        - mysql
        - redis
        - phpfpm
    ports:
        - "80:80"
    volumes:
        - /var/www:/usr/share/nginx/html

mysql:
    image: index.alauda.cn/library/mysql
    environment:
        MYSQL_ROOT_PASSWORD: chqy10725
    ports:
        - "3306:3306"

redis:
    image: index.alauda.cn/library/redis
    ports:
        - "6379:6379"

phpfpm:
    image: php-fpm:v5.6
    volumes:
        - /var/www/html:/usr/share/nginx/html
    ports:
        - "9000:9000"
