FROM index.alauda.cn/library/ubuntu:16.04
MAINTAINER	chenishr@gmail.com

# 安装 vim git 和一些编译工具和依赖包
RUN apt-get update && \
	apt-get install -y vim && \
	apt-get install -y git 

#RUN	apt-get install -y \
#		build-essential \
#		gcc \
#		g++ \
#		autoconf \
#		libiconv-hook-dev \
#		libmcrypt-dev \
#		libxml2-dev \
#		libmysqlclient-dev \
#		libcurl4-openssl-dev \
#		libjpeg8-dev \
#		libpng12-dev \
#		libfreetype6-dev 

# 容器的启动脚本,运行一个挂起的命令，保持容器不自动退出
COPY	my_init.sh /sbin/my_init.sh
RUN		chmod 755 /sbin/my_init.sh

WORKDIR /var/www/html
ENTRYPOINT	["/sbin/my_init.sh"]
